In [767]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sb
from sklearn.model_selection import train_test_split
import warnings
warnings.filterwarnings('ignore')

In [768]:
dp=pd.read_csv('data.csv')
dp=dp.dropna()
dp.shape

(563, 32)

In [769]:
dp.drop(['id'],axis=1,inplace=True)
Y=dp['diagnosis']
dp.drop(['diagnosis'],axis=1,inplace=True)
X=dp

In [770]:
Y = Y.replace({'B': 1, 'M': 0})
Y=Y.to_numpy()
Y.shape=(Y.shape[0],1)

In [771]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.33, shuffle=False)
print(X_train.shape,X_test.shape,Y_train.shape,Y_test.shape)
X_train.head()

(377, 30) (186, 30) (377, 1) (186, 1)


radius_mean  texture_mean  perimeter_mean  area_mean  smoothness_mean  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   compactness_mean  concavity_mean  concave points_mean  symmetry_mean  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   fractal_dimension_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0                 0.07871  ...         25.38          17.33           184.60   
1                 0.05667  ...         24.99          23.41           158.80   
2                 0.05999  ...         23.57          25.53           152.50   
3                 0.09744  ...         14.91          26.50            98.87   
4                 0.05883  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 30 columns]

In [780]:
def sigmoid(z):
    return 1/(1+np.exp(-z))

def cost_function(X,Y,w,b):
    m=X.shape[0]
    y_pred=sigmoid(np.dot(X,w)+b)
    cost=(-1/m)*np.sum(Y*np.log(y_pred)+(1-Y)*np.log(1-y_pred))
    return cost

def stochastic_gradient_descent(X,Y,w,b,learning_rate,iterations):
    m=X.shape[0]
    cost_list=[]
    for i in range(iterations):
        y_pred=sigmoid(np.dot(X,w)+b)
        w=w-(learning_rate/m)*np.dot(X.T,(y_pred-Y))
        b=b-(learning_rate/m)*np.sum(y_pred-Y)
        cost=cost_function(X,Y,w,b)
        cost_list.append(cost)
    return w,b,cost_list

def predict(X,w,b):
    y_pred=sigmoid(np.dot(X,w)+b)
    y_pred=np.where(y_pred>0.5,1,0)
    return y_pred

def accuracy(y_pred,Y_test):
    y_pred=y_pred.reshape(Y_test.shape)
    return (np.sum(y_pred==Y_test)/Y_test.shape[0])*100

In [784]:
#initializing the parameters
w=np.zeros((X_train.shape[1],1))
b=0
w,b,cost_list=stochastic_gradient_descent(X_train,Y_train,w,b,learning_rate=0.01,iterations=100000)
print("The value weights for all the features is: ")
print(w)
print("The value of the bias is: ")
print(b)
y_pred=predict(X_test,w,b)
print("The accuracy of the model is: ")
print(accuracy(y_pred,Y_test))

Cost after 0 iterations is nan
Cost after 1000 iterations is nan
Cost after 2000 iterations is nan
Cost after 3000 iterations is nan
Cost after 4000 iterations is nan
Cost after 5000 iterations is nan
Cost after 6000 iterations is nan
Cost after 7000 iterations is nan
Cost after 8000 iterations is nan
Cost after 9000 iterations is nan
Cost after 10000 iterations is nan
Cost after 11000 iterations is nan
Cost after 12000 iterations is nan
Cost after 13000 iterations is nan
Cost after 14000 iterations is nan
Cost after 15000 iterations is nan
Cost after 16000 iterations is nan
Cost after 17000 iterations is nan
Cost after 18000 iterations is nan
Cost after 19000 iterations is nan
Cost after 20000 iterations is nan
Cost after 21000 iterations is nan
Cost after 22000 iterations is nan
Cost after 23000 iterations is nan
Cost after 24000 iterations is nan
Cost after 25000 iterations is nan
Cost after 26000 iterations is nan
Cost after 27000 iterations is nan
Cost after 28000 iterations is na

In [ ]:
#initializing the parameters
w=np.zeros((X_train.shape[1],1))
b=0
w,b,cost_list=stochastic_gradient_descent(X_train,Y_train,w,b,learning_rate=0.001,iterations=100000)
print("The value weights for all the features is: ")
print(w)
print("The value of the bias is: ")
print(b)
y_pred=predict(X_test,w,b)
print("The accuracy of the model is: ")
print(accuracy(y_pred,Y_test))

The value weights for all the features is: 
[[ 3.23655485e+00]
 [-3.45190695e-01]
 [ 7.73037407e+00]
 [-1.18133819e-01]
 [-4.90337373e-02]
 [-3.52023962e-01]
 [-5.10027698e-01]
 [-2.01304634e-01]
 [-7.67269762e-02]
 [-1.55251089e-02]
 [ 9.46777469e-02]
 [ 6.01652783e-01]
 [-7.59694853e-01]
 [-1.30294356e+00]
 [-6.46527196e-03]
 [-8.75772012e-02]
 [-1.17200142e-01]
 [-2.49751361e-02]
 [-2.66110385e-02]
 [-7.33436954e-03]
 [ 3.38716609e+00]
 [-4.25143241e+00]
 [-1.42886151e+00]
 [-5.41324269e-01]
 [-1.16205576e-01]
 [-1.13356467e+00]
 [-1.43725793e+00]
 [-3.72479970e-01]
 [-3.09250662e-01]
 [-9.23239527e-02]]
The value of the bias is: 
0.4511507365687659
The accuracy of the model is: 
92.47311827956989


In [611]:
#initializing the parameters
w=np.zeros((X_train.shape[1],1))
b=0
w,b,cost_list=stochastic_gradient_descent(X_train,Y_train,w,b,learning_rate=0.0001,iterations=100000)
print("The value weights for all the features is: ")
print(w)
print("The value of the bias is: ")
print(b)
y_pred=predict(X_test,w,b)
print("The accuracy of the model is: ")
print(accuracy(y_pred,Y_test))

The value weights for all the features is: 
[[ 3.27641006e-01]
 [-2.62514570e-02]
 [ 7.72318815e-01]
 [-1.49762072e-02]
 [-4.91508892e-03]
 [-3.62240463e-02]
 [-5.22002703e-02]
 [-2.05007404e-02]
 [-7.89622397e-03]
 [-1.54421251e-03]
 [ 9.76902430e-03]
 [ 6.28181687e-02]
 [-7.90213742e-02]
 [-1.27140561e-01]
 [-6.51679343e-04]
 [-9.25688658e-03]
 [-1.21069629e-02]
 [-2.56498603e-03]
 [-2.59659559e-03]
 [-7.71922676e-04]
 [ 3.42229360e-01]
 [-3.90036236e-01]
 [-1.79840613e-01]
 [-4.77090478e-02]
 [-1.15853436e-02]
 [-1.19201835e-01]
 [-1.48837573e-01]
 [-3.84380191e-02]
 [-3.19848088e-02]
 [-9.72059401e-03]]
The value of the bias is: 
0.04706959104219963
The accuracy of the model is: 
95.6989247311828


In [612]:
def sigmoid(z):
    return 1/(1+np.exp(-z))

def cost_function(X,Y,w,b):
    m=X.shape[0]
    y_pred=sigmoid(np.dot(X,w)+b)
    cost=(-1/m)*np.sum(Y*np.log(y_pred)+(1-Y)*np.log(1-y_pred))
    return cost

def mini_batch_gradient_descent(X,Y,w,b,learning_rate,iterations,batch_size):
    m=X.shape[0]
    cost_list=[]
    for i in range(iterations):
        for j in range(0,m,batch_size):
            X=pd.DataFrame(X)
            Y=pd.DataFrame(Y)
            X_batch=X.iloc[j:j+batch_size,:]
            Y_batch=Y.iloc[j:j+batch_size,:]
            X_batch=X_batch.to_numpy()
            Y_batch=Y_batch.to_numpy()
            y_pred=sigmoid(np.dot(X_batch,w)+b)
            w=w-(learning_rate/m)*np.dot(X_batch.T,(y_pred-Y_batch))
            b=b-(learning_rate/m)*np.sum(y_pred-Y_batch)
        cost=cost_function(X,Y,w,b)
        cost_list.append(cost)
    return w,b,cost_list

def predict(X,w,b):
    y_pred=sigmoid(np.dot(X,w)+b)
    y_pred=np.where(y_pred>0.5,1,0)
    return y_pred

def accuracy(y_pred,Y_test):
    y_pred=y_pred.reshape(Y_test.shape)
    return (np.sum(y_pred==Y_test)/Y_test.shape[0])*100

In [613]:
#initializing the parameters
w=np.zeros((X_train.shape[1],1))
b=0
w,b,cost_list=mini_batch_gradient_descent(X_train,Y_train,w,b,learning_rate=0.01,iterations=10000,batch_size=32)
print("The value weights for all the features is: ")
print(w)
print("The value of the bias is: ")
print(b)
y_pred=predict(X_test,w,b)
print("The accuracy of the model is: ")
print(accuracy(y_pred,Y_test))

The value weights for all the features is: 
[[ 3.30310548e+00]
 [-1.65962117e+00]
 [ 8.21840324e+00]
 [-1.19595672e-01]
 [-4.44626931e-02]
 [-3.40001901e-01]
 [-5.08003715e-01]
 [-1.99366735e-01]
 [-7.46968271e-02]
 [-1.61119426e-02]
 [ 5.88740262e-02]
 [ 8.88125311e-01]
 [-1.15230469e+00]
 [-9.75753218e-01]
 [-5.09493350e-03]
 [-8.32483934e-02]
 [-1.11658905e-01]
 [-2.62977989e-02]
 [-2.27792372e-02]
 [-6.85426861e-03]
 [ 3.22068729e+00]
 [-2.96245049e+00]
 [-2.22310993e+00]
 [-4.05185067e-01]
 [-1.10158459e-01]
 [-1.15530582e+00]
 [-1.40878988e+00]
 [-3.84028258e-01]
 [-3.29469062e-01]
 [-9.52174900e-02]]
The value of the bias is: 
0.4446229300566273
The accuracy of the model is: 
91.93548387096774


In [614]:
#initializing the parameters
w=np.zeros((X_train.shape[1],1))
b=0
w,b,cost_list=mini_batch_gradient_descent(X_train,Y_train,w,b,learning_rate=0.001,iterations=10000,batch_size=32)
print("The value weights for all the features is: ")
print(w)
print("The value of the bias is: ")
print(b)
y_pred=predict(X_test,w,b)
print("The accuracy of the model is: ")
print(accuracy(y_pred,Y_test))

The value weights for all the features is: 
[[ 3.14047067e-01]
 [-1.15996495e-01]
 [ 7.57257955e-01]
 [-1.65245611e-02]
 [-4.30220773e-03]
 [-3.28865315e-02]
 [-4.80789013e-02]
 [-1.92507692e-02]
 [-7.70412411e-03]
 [-1.46464613e-03]
 [ 4.95265559e-03]
 [ 8.51985395e-02]
 [-1.13588439e-01]
 [-7.13587561e-02]
 [-5.25592898e-04]
 [-7.58126847e-03]
 [-1.00750299e-02]
 [-2.48883459e-03]
 [-2.04948800e-03]
 [-6.24443918e-04]
 [ 3.09252838e-01]
 [-2.54586382e-01]
 [-2.39357259e-01]
 [-3.01854581e-02]
 [-1.16103041e-02]
 [-1.12679162e-01]
 [-1.34041794e-01]
 [-3.74544304e-02]
 [-3.33456463e-02]
 [-9.26228223e-03]]
The value of the bias is: 
0.043983237682981374
The accuracy of the model is: 
91.39784946236558


In [615]:
#initializing the parameters
w=np.zeros((X_train.shape[1],1))
b=0
w,b,cost_list=mini_batch_gradient_descent(X_train,Y_train,w,b,learning_rate=0.0001,iterations=10000,batch_size=32)
print("The value weights for all the features is: ")
print(w)
print("The value of the bias is: ")
print(b)
y_pred=predict(X_test,w,b)
print("The accuracy of the model is: ")
print(accuracy(y_pred,Y_test))

The value weights for all the features is: 
[[ 5.04123428e-02]
 [-3.00909196e-02]
 [ 1.69311181e-01]
 [ 6.70253810e-03]
 [-2.86654669e-04]
 [-3.88830742e-03]
 [-5.84750516e-03]
 [-2.29343611e-03]
 [-3.44644380e-04]
 [ 1.75067674e-05]
 [ 1.03202708e-03]
 [ 4.45469151e-03]
 [-1.16056286e-02]
 [-3.20672418e-02]
 [-6.64627045e-05]
 [-1.06958825e-03]
 [-1.38804525e-03]
 [-3.06220454e-04]
 [-1.88754101e-04]
 [-8.33015697e-05]
 [ 5.15385725e-02]
 [-8.79315611e-02]
 [ 3.90412425e-02]
 [-2.63967424e-02]
 [-9.04806736e-04]
 [-1.36071287e-02]
 [-1.70114966e-02]
 [-4.46739294e-03]
 [-2.85505189e-03]
 [-9.31666539e-04]]
The value of the bias is: 
0.007812133626855591
The accuracy of the model is: 
96.23655913978494


In [616]:
def sigmoid(z):
    return 1/(1+np.exp(-z))

def cost_function(X,Y,w,b):
    m=X.shape[0]
    y_pred=sigmoid(np.dot(X,w)+b)
    cost=(-1/m)*np.sum(Y*np.log(y_pred)+(1-Y)*np.log(1-y_pred))
    return cost

def batch_gradient_descent(X,Y,w,b,learning_rate,iterations,batch_size):
    m=X.shape[0]
    cost_list=[]
    for i in range(iterations):
        for j in range(0,m,batch_size):
            X=pd.DataFrame(X)
            Y=pd.DataFrame(Y)
            X_batch=X.iloc[j:j+batch_size,:]
            Y_batch=Y.iloc[j:j+batch_size,:]
            X_batch=X_batch.to_numpy()
            Y_batch=Y_batch.to_numpy()
            y_pred=sigmoid(np.dot(X_batch,w)+b)
        w=w-(learning_rate/m)*np.dot(X_batch.T,(y_pred-Y_batch))
        b=b-(learning_rate/m)*np.sum(y_pred-Y_batch)
        cost=cost_function(X,Y,w,b)
        cost_list.append(cost)
    return w,b,cost_list

def predict(X,w,b):
    y_pred=sigmoid(np.dot(X,w)+b)
    y_pred=np.where(y_pred>0.5,1,0)
    return y_pred

def accuracy(y_pred,Y_test):
    y_pred=y_pred.reshape(Y_test.shape)
    return (np.sum(y_pred==Y_test)/Y_test.shape[0])*100

In [619]:
#initializing the parameters
w=np.zeros((X_train.shape[1],1))
b=0
w,b,cost_list=batch_gradient_descent(X_train,Y_train,w,b,learning_rate=0.01,iterations=10000,batch_size=32)
print("The value weights for all the features is: ")
print(w)
print("The value of the bias is: ")
print(b)
y_pred=predict(X_test,w,b)
print("The accuracy of the model is: ")
print(accuracy(y_pred,Y_test))

In [16]:
w=np.zeros((X_train.shape[1],1))
b=0
w,b,cost_list=batch_gradient_descent(X_train,Y_train,w,b,learning_rate=0.001,iterations=10000,batch_size=32)
print("The value weights for all the features is: ")
print(w)
print("The value of the bias is: ")
print(b)
y_pred=predict(X_test,w,b)
print("The accuracy of the model is: ")
print(accuracy(y_pred,Y_test))

The value weights for all the features is: 
[[ 6.98567740e-02]
 [-4.72541910e-02]
 [ 3.52660067e-01]
 [ 4.99999358e-02]
 [ 2.08154803e-04]
 [-1.51986947e-03]
 [-4.02359254e-03]
 [-2.35326070e-03]
 [-3.16612054e-04]
 [ 3.70182453e-04]
 [ 3.15774094e-04]
 [-2.31578581e-02]
 [-1.65099518e-02]
 [ 1.21897364e-01]
 [-1.25300055e-04]
 [-5.49885551e-04]
 [-8.18196246e-04]
 [-3.49353044e-04]
 [-2.56118167e-04]
 [-5.85057867e-05]
 [ 6.07637381e-02]
 [-1.91870500e-01]
 [ 1.95714264e-01]
 [-1.00780870e-01]
 [-7.21935034e-04]
 [-5.36486728e-03]
 [-1.01145756e-02]
 [-4.73275659e-03]
 [-1.94682449e-03]
 [-2.13752120e-04]]
The value of the bias is: 
0.009705190449300377
The accuracy of the model is: 
93.01075268817203


In [17]:
w=np.zeros((X_train.shape[1],1))
b=0
w,b,cost_list=batch_gradient_descent(X_train,Y_train,w,b,learning_rate=0.0001,iterations=10000,batch_size=32)
print("The value weights for all the features is: ")
print(w)
print("The value of the bias is: ")
print(b)
y_pred=predict(X_test,w,b)
print("The accuracy of the model is: ")
print(accuracy(y_pred,Y_test))

The value weights for all the features is: 
[[ 1.08774056e-02]
 [ 2.25578350e-03]
 [ 5.93895834e-02]
 [ 1.50751007e-02]
 [ 8.01435849e-05]
 [-1.24091339e-04]
 [-4.27070164e-04]
 [-2.52098575e-04]
 [ 7.81235245e-05]
 [ 7.93177565e-05]
 [ 2.38784951e-04]
 [-1.74636269e-03]
 [-1.78913346e-04]
 [ 2.32499296e-02]
 [-7.31989334e-06]
 [-3.82524915e-05]
 [-7.69279282e-05]
 [-3.21831368e-05]
 [-7.53857040e-06]
 [-1.33111163e-06]
 [ 9.88563358e-03]
 [-1.28423105e-02]
 [ 4.36381238e-02]
 [-2.47795805e-02]
 [-9.99149024e-06]
 [-5.44964967e-04]
 [-1.12299290e-03]
 [-5.17428169e-04]
 [-4.53403553e-05]
 [ 1.55965944e-05]]
The value of the bias is: 
0.0015735133461336947
The accuracy of the model is: 
92.47311827956989
